url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Siyuan Ma" # the name of your site, e.g. ACME Corp.
description: "Postdoctoral researcher at the University of Pennsylvania"
